name: Test Push

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "test" > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt