name: Test Simple

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Test API
        run: |
          gh auth status
          gh repo view odzorp/About-me --jq '.name'