name: Test Simple

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test gh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --hostname github.com --with-token
          gh api user --jq '.login'